version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/eir_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eir_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs-server
    profiles:
      - docs
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    working_dir: /docs
    entrypoint: []
    command: >
      mkdocs serve -a 0.0.0.0:8000

volumes:
  postgres_data:
