name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-test:
    name: Build and Test with Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose-plugin

      - name: Build and Test Application
        run: |
          docker compose up --build -d
          sleep 10  # Allow services to initialize
          docker compose exec fastapi-app /app/.venv/bin/pytest app/test_main.py
        env:
          DATABASE_URL: postgresql://postgres:postgres@db:5432/mydatabase

      - name: Stop and Clean Docker Containers
        run: docker compose down --volumes

  deploy-docs:
    name: Deploy Documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Cache MkDocs Dependencies
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Deploy Documentation
        run: mkdocs gh-deploy --force
